name: document_client
description: |
  The DynamoDB document client simplifies working with items.
  It uses native Dart types as input parameters, as well as converts response data to native Dart types.
version: 2.0.0

homepage: https://github.com/agilord/aws_client

environment:
  sdk: "^3.0.0"

dependencies:
  aws_dynamodb_api:
    git:
      url: https://github.com/brighttank/aws_client.git
      path: generated/aws_dynamodb_api
  shared_aws_api:
    git:
      url: https://github.com/brighttank/aws_client.git
      path: shared_aws_api

dev_dependencies:
  lints:
  test:
  http:
