name: shared_aws_api
description: Shared protocol implementation and utilities for generated AWS API clients.
version: 2.0.1

homepage: https://github.com/agilord/aws_client/tree/master/shared_aws_api

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  http: '>=0.13.1 <2.0.0'
  meta: ^1.9.0 # pinned by flutter
  xml:  '>=6.0.0 <7.0.0'
  intl: ^0.18.1
  uuid: ^3.0.7 # leave on v3 for compatibility with other packages
  collection: ^1.17.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.8
